#pragma once

const char INDEX_HTML[] PROGMEM = R"ATOMDECKHTML(
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AtomDeck-S3</title><style>
:root{color-scheme:dark;--bg:#07111f;--panel:#102136;--line:#29415d;--text:#edf6ff;--muted:#9bb1c8;--blue:#42a5f5;--green:#53d18d;--red:#ff6b7a}*{box-sizing:border-box}body{margin:0;background:linear-gradient(140deg,#06101d,#10243a);color:var(--text);font:15px system-ui,sans-serif;min-height:100vh}.wrap{max-width:980px;margin:auto;padding:28px 18px 60px}header{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}h1{margin:0;font-size:28px}.sub{color:var(--muted);margin-top:5px}.chip{padding:7px 12px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.chip.on{border-color:var(--green);color:var(--green)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:rgba(16,33,54,.94);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 12px 32px #0004}.wide{grid-column:1/-1}h2{font-size:18px;margin:0 0 14px}label{display:block;color:var(--muted);font-size:13px;margin:12px 0 5px}input,textarea{width:100%;background:#071522;border:1px solid var(--line);color:var(--text);padding:10px 11px;border-radius:9px;font:inherit}textarea{min-height:150px;font-family:ui-monospace,monospace;resize:vertical}button{border:0;border-radius:9px;padding:10px 14px;background:var(--blue);color:#04101a;font-weight:700;cursor:pointer}button.secondary{background:#29415d;color:var(--text)}button.danger{background:var(--red)}button:disabled{opacity:.45;cursor:not-allowed}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.macro,.token{display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid var(--line);padding:12px 0}.macro:first-child,.token:first-child{border-top:0}.name{font-weight:700}.meta,.hint{color:var(--muted);font-size:13px}.notice{padding:12px;border:1px solid #795b20;background:#2b2514;border-radius:10px;margin-bottom:14px}.secret{padding:12px;border:1px solid var(--green);background:#0a2c22;border-radius:10px;margin-top:12px;overflow-wrap:anywhere}.secret code{display:block;margin-top:8px;user-select:all}.ok{color:var(--green)}.error{color:var(--red)}#toast{position:fixed;right:18px;bottom:18px;max-width:360px;padding:12px 15px;border-radius:10px;background:#152b42;border:1px solid var(--line);display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="wrap"><header><div><h1>AtomDeck-S3</h1><div class="sub" id="device">正在读取设备状态…</div></div><div class="row"><div id="armed" class="chip">未授权</div><button id="logoutBtn" class="secondary" hidden>退出</button></div></header>
<div id="setup" class="card wide" hidden><h2>家庭 Wi-Fi 与管理员设置</h2><div class="notice">临时设置网络为开放网络，并将在十分钟后关闭。配置内容不会回显或写入日志。</div><form id="wifiForm"><label>Wi-Fi SSID</label><input id="ssid" maxlength="32" autocomplete="off" required><label>Wi-Fi 密码</label><input id="wifiPassword" type="password" maxlength="63" autocomplete="new-password"><label id="setupAdminLabel">创建管理员密码</label><input id="setupAdmin" type="password" minlength="12" maxlength="72" autocomplete="new-password" required><div id="setupAdminHint" class="hint">12–72 字节，须同时包含字母和数字、空格或符号。</div><label id="setupConfirmLabel">确认管理员密码</label><input id="setupConfirm" type="password" minlength="12" maxlength="72" autocomplete="new-password"><div class="row" style="margin-top:14px"><button>保存并重启</button></div></form></div>
<div id="login" class="card" hidden><h2>管理员登录</h2><div class="hint">请输入首次设置时创建的管理员密码。</div><form id="loginForm"><label>管理员密码</label><input id="loginPassword" type="password" maxlength="72" autocomplete="current-password" required><div class="row" style="margin-top:14px"><button>登录</button></div></form></div>
<div id="main" class="grid" hidden><section class="card"><h2>直接输入</h2><div class="hint">请先按一次 AtomS3U 实体按钮；只有点击“输入”时才会发送文本。</div><label>文本</label><textarea id="directText" maxlength="256" placeholder="简短且不含秘密的文本…"></textarea><div class="row"><button id="typeBtn" data-arm>输入</button></div></section>
<section class="card"><h2>鼠标</h2><div class="hint">仅执行小幅、明确的操作；每个命令都需要实体授权。</div><div class="row" style="justify-content:center;margin:16px 0"><button data-arm data-mouse='{"op":"move","x":0,"y":-20}'>↑</button></div><div class="row" style="justify-content:center"><button data-arm data-mouse='{"op":"move","x":-20,"y":0}'>←</button><button data-arm data-mouse='{"op":"click","button":"LEFT"}'>左键</button><button data-arm data-mouse='{"op":"move","x":20,"y":0}'>→</button></div><div class="row" style="justify-content:center;margin:10px 0"><button data-arm data-mouse='{"op":"move","x":0,"y":20}'>↓</button><button data-arm data-mouse='{"op":"click","button":"RIGHT"}'>右键</button></div><div class="row" style="justify-content:center"><button data-arm data-mouse='{"op":"scroll","amount":-3}'>向上滚动</button><button data-arm data-mouse='{"op":"scroll","amount":3}'>向下滚动</button></div></section>
<section class="card"><h2>Macro 编辑器</h2><input id="macroId" type="hidden"><label>名称</label><input id="macroName" maxlength="48" placeholder="例如：插入签名"><label>动作（JSON 数组）</label><textarea id="actions">[
  {"type":"text","value":"Hello from AtomDeck-S3"},
  {"type":"key","value":"ENTER"}
]</textarea><div class="hint">允许 text、key、chord、delay 与受限鼠标动作；不支持脚本或系统命令。</div><div class="row" style="margin-top:12px"><button id="saveBtn" data-arm>保存 Macro</button><button id="cancelBtn" class="secondary" type="button">清空</button></div></section>
<section class="card"><h2>REST API Token</h2><div class="hint">Token 只在创建时显示一次；设备只保存哈希。创建和撤销均需实体授权。</div><label>Token 名称</label><input id="tokenName" maxlength="32" placeholder="例如：家庭自动化" required><div class="row" style="margin-top:12px"><button id="createTokenBtn" data-arm>创建 Token</button></div><div id="newToken" class="secret" hidden><strong>请立即复制并安全保存：</strong><code id="newTokenValue"></code></div><div id="tokens" style="margin-top:12px"></div></section>
<section class="card"><h2>修改管理员密码</h2><div class="hint">修改需要实体授权，成功后所有浏览器会话失效；已有 API Token 保持有效，可在上方单独撤销。</div><form id="passwordForm"><label>当前密码</label><input id="currentPassword" type="password" maxlength="72" autocomplete="current-password" required><label>新密码</label><input id="newPassword" type="password" minlength="12" maxlength="72" autocomplete="new-password" required><label>确认新密码</label><input id="confirmPassword" type="password" minlength="12" maxlength="72" autocomplete="new-password" required><div class="row" style="margin-top:12px"><button data-arm>修改密码</button></div></form></section>
<section class="card wide"><div class="row" style="justify-content:space-between"><h2>已保存的 Macro</h2><button id="refreshBtn" class="secondary">刷新</button></div><div id="macros"><span class="hint">正在加载…</span></div></section></div></div><div id="toast"></div>
<script>
const $=s=>document.querySelector(s);let state={},macros=[],authenticated=false;function toast(m,bad=false){const t=$('#toast');t.textContent=m;t.className=bad?'error':'ok';t.style.display='block';setTimeout(()=>t.style.display='none',3500)}async function api(path,opt={}){opt.credentials='same-origin';opt.headers={Accept:'application/json',...(opt.headers||{})};if(opt.body)opt.headers['Content-Type']='application/json';const r=await fetch(path,opt);let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data.error||`HTTP ${r.status}`);e.status=r.status;throw e}return data}
function updateViews(){const setup=!!state.setup_mode;$('#setup').hidden=!setup;$('#login').hidden=setup||authenticated;$('#main').hidden=setup||!authenticated;$('#logoutBtn').hidden=setup||!authenticated;if(setup){const existing=!!state.auth_configured;$('#setupAdminLabel').textContent=existing?'现有管理员密码':'创建管理员密码';$('#setupAdminHint').textContent=existing?'重新配置网络前需验证现有管理员密码。':'12–72 字节，须同时包含字母和数字、空格或符号。';$('#setupConfirmLabel').hidden=existing;$('#setupConfirm').hidden=existing;$('#setupConfirm').required=!existing;$('#setupAdmin').autocomplete=existing?'current-password':'new-password'}document.querySelectorAll('[data-arm]').forEach(b=>b.disabled=!state.armed)}
async function status(){state=await api('/api/v1/status');$('#device').textContent=`${state.hostname} · ${state.wifi.ip} · ${state.wifi.mode} · v${state.version}`;const a=$('#armed');a.textContent=state.armed?`已授权 · ${state.armed_seconds} 秒`:'未授权 · 请按设备按钮';a.classList.toggle('on',state.armed);updateViews()}
async function checkLogin(){try{await api('/api/v1/auth/me');authenticated=true;updateViews();await Promise.all([loadMacros(),loadTokens()])}catch(e){authenticated=false;updateViews();if(e.status!==401)toast(e.message,true)}}
function render(){const host=$('#macros');host.innerHTML='';if(!macros.length){host.innerHTML='<span class="hint">尚未保存 Macro。</span>';return}for(const m of macros){const el=document.createElement('div');el.className='macro';el.innerHTML='<div><div class="name"></div><div class="meta"></div></div><div class="row"><button class="run" data-arm>运行</button><button class="edit secondary">编辑</button><button class="del danger" data-arm>删除</button></div>';el.querySelector('.name').textContent=m.name;el.querySelector('.meta').textContent=`${m.actions.length} 个动作 · ${m.id.slice(0,8)}`;el.querySelectorAll('[data-arm]').forEach(b=>b.disabled=!state.armed);el.querySelector('.run').onclick=async()=>{try{await api(`/api/v1/macros/${m.id}/run`,{method:'POST'});toast('Macro 执行完成')}catch(e){handleError(e)}};el.querySelector('.edit').onclick=()=>{$('#macroId').value=m.id;$('#macroName').value=m.name;$('#actions').value=JSON.stringify(m.actions,null,2);scrollTo({top:0,behavior:'smooth'})};el.querySelector('.del').onclick=async()=>{if(!confirm(`确定删除“${m.name}”？`))return;try{await api(`/api/v1/macros/${m.id}`,{method:'DELETE'});toast('Macro 已删除');await loadMacros()}catch(e){handleError(e)}};host.append(el)}}
async function loadMacros(){macros=await api('/api/v1/macros');render()}function clearEditor(){$('#macroId').value='';$('#macroName').value='';$('#actions').value='[\n  {"type":"text","value":""}\n]'}function handleError(e){if(e.status===401){authenticated=false;updateViews();toast('登录已失效，请重新登录',true)}else toast(e.message,true)}
function renderTokens(tokens){const host=$('#tokens');host.innerHTML='';if(!tokens.length){host.innerHTML='<span class="hint">尚未创建 Token。</span>';return}for(const t of tokens){const el=document.createElement('div');el.className='token';el.innerHTML='<div><div class="name"></div><div class="meta"></div></div><button class="danger revoke" data-arm>撤销</button>';el.querySelector('.name').textContent=t.name;el.querySelector('.meta').textContent=t.id;el.querySelector('.revoke').disabled=!state.armed;el.querySelector('.revoke').onclick=async()=>{if(!confirm(`撤销 Token“${t.name}”？`))return;try{await api(`/api/v1/tokens/${t.id}`,{method:'DELETE'});$('#newToken').hidden=true;await loadTokens();toast('Token 已撤销')}catch(e){handleError(e)}};host.append(el)}}async function loadTokens(){renderTokens(await api('/api/v1/tokens'))}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({password:$('#loginPassword').value})});$('#loginPassword').value='';authenticated=true;updateViews();await Promise.all([loadMacros(),loadTokens()]);toast('登录成功')}catch(err){$('#loginPassword').value='';toast(err.message,true)}};$('#logoutBtn').onclick=async()=>{try{await api('/api/v1/auth/logout',{method:'POST'})}catch{}authenticated=false;$('#newToken').hidden=true;updateViews()};
$('#saveBtn').onclick=async()=>{try{const payload={name:$('#macroName').value,actions:JSON.parse($('#actions').value)};const id=$('#macroId').value;await api(id?`/api/v1/macros/${id}`:'/api/v1/macros',{method:id?'PUT':'POST',body:JSON.stringify(payload)});toast(id?'Macro 已更新':'Macro 已创建');clearEditor();await loadMacros()}catch(e){handleError(e)}};$('#cancelBtn').onclick=clearEditor;$('#refreshBtn').onclick=async()=>{try{await Promise.all([status(),loadMacros(),loadTokens()])}catch(e){handleError(e)}};$('#typeBtn').onclick=async()=>{try{await api('/api/v1/type',{method:'POST',body:JSON.stringify({text:$('#directText').value})});toast('文本已输入')}catch(e){handleError(e)}};
$('#createTokenBtn').onclick=async()=>{try{const result=await api('/api/v1/tokens',{method:'POST',body:JSON.stringify({name:$('#tokenName').value})});$('#tokenName').value='';$('#newTokenValue').textContent=result.token;$('#newToken').hidden=false;await loadTokens();toast('Token 已创建，只显示这一次')}catch(e){handleError(e)}};
$('#passwordForm').onsubmit=async e=>{e.preventDefault();if($('#newPassword').value!==$('#confirmPassword').value)return toast('两次输入的新密码不一致',true);try{await api('/api/v1/auth/password',{method:'POST',body:JSON.stringify({current_password:$('#currentPassword').value,new_password:$('#newPassword').value})});e.target.reset();authenticated=false;updateViews();toast('密码已修改，请重新登录')}catch(err){e.target.reset();handleError(err)}};
$('#wifiForm').onsubmit=async e=>{e.preventDefault();if(!state.auth_configured&&$('#setupAdmin').value!==$('#setupConfirm').value)return toast('两次输入的管理员密码不一致',true);try{await api('/api/v1/wifi',{method:'POST',body:JSON.stringify({ssid:$('#ssid').value,password:$('#wifiPassword').value,admin_password:$('#setupAdmin').value})});e.target.reset();toast('已保存，设备正在重启…')}catch(err){$('#wifiPassword').value='';$('#setupAdmin').value='';$('#setupConfirm').value='';toast(err.message,true)}};
document.querySelectorAll('[data-mouse]').forEach(b=>b.onclick=async()=>{try{await api('/api/v1/mouse',{method:'POST',body:b.dataset.mouse});toast('鼠标命令已发送')}catch(e){handleError(e)}});
(async()=>{try{await status();if(!state.setup_mode)await checkLogin();setInterval(async()=>{try{await status()}catch{}},1000)}catch(e){toast(e.message,true)}})();
</script></body></html>
)ATOMDECKHTML";
