#pragma once

const char INDEX_HTML[] PROGMEM = R"ATOMDECKHTML(
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AtomDeck-S3</title><style>
:root{color-scheme:dark;--bg:#07111f;--panel:#102136;--line:#29415d;--text:#edf6ff;--muted:#9bb1c8;--blue:#42a5f5;--green:#53d18d;--red:#ff6b7a}*{box-sizing:border-box}body{margin:0;background:linear-gradient(140deg,#06101d,#10243a);color:var(--text);font:15px system-ui,sans-serif;min-height:100vh}.wrap{max-width:980px;margin:auto;padding:28px 18px 60px}header{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}h1{margin:0;font-size:28px}.sub{color:var(--muted);margin-top:5px}.chip{padding:7px 12px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.chip.on{border-color:var(--green);color:var(--green)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:rgba(16,33,54,.94);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 12px 32px #0004}.wide{grid-column:1/-1}h2{font-size:18px;margin:0 0 14px}label{display:block;color:var(--muted);font-size:13px;margin:12px 0 5px}input,textarea,select{width:100%;background:#071522;border:1px solid var(--line);color:var(--text);padding:10px 11px;border-radius:9px;font:inherit}textarea{min-height:150px;font-family:ui-monospace,monospace;resize:vertical}button{border:0;border-radius:9px;padding:10px 14px;background:var(--blue);color:#04101a;font-weight:700;cursor:pointer}button.secondary{background:#29415d;color:var(--text)}button.danger{background:var(--red)}button:disabled{opacity:.45;cursor:not-allowed}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.macro{display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid var(--line);padding:12px 0}.macro:first-child{border-top:0}.name{font-weight:700}.meta,.hint{color:var(--muted);font-size:13px}.notice{padding:12px;border:1px solid #795b20;background:#2b2514;border-radius:10px;margin-bottom:14px}.ok{color:var(--green)}.error{color:var(--red)}#toast{position:fixed;right:18px;bottom:18px;max-width:360px;padding:12px 15px;border-radius:10px;background:#152b42;border:1px solid var(--line);display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="wrap"><header><div><h1>AtomDeck-S3</h1><div class="sub" id="device">正在读取设备状态…</div></div><div id="armed" class="chip">未授权</div></header>
<div id="setup" class="card wide" hidden><h2>家庭 Wi-Fi 设置</h2><div class="notice">此临时设置网络为开放网络，并将在十分钟后关闭。请尽快完成配置。</div><form id="wifiForm"><label>Wi-Fi SSID</label><input id="ssid" maxlength="32" autocomplete="off" required><label>密码</label><input id="password" type="password" minlength="8" maxlength="63" autocomplete="new-password"><div class="row" style="margin-top:14px"><button>保存并重启</button></div></form></div>
<div id="main" class="grid"><section class="card"><h2>直接输入</h2><div class="hint">请先按一次 AtomS3U 实体按钮；只有点击“输入”时才会发送文本。</div><label>文本</label><textarea id="directText" maxlength="256" placeholder="简短且不含秘密的文本…"></textarea><div class="row"><button id="typeBtn">输入</button></div></section>
<section class="card"><h2>鼠标</h2><div class="hint">仅执行小幅、明确的操作；每个命令都需要实体授权。</div><div class="row" style="justify-content:center;margin:16px 0"><button data-mouse='{"op":"move","x":0,"y":-20}'>↑</button></div><div class="row" style="justify-content:center"><button data-mouse='{"op":"move","x":-20,"y":0}'>←</button><button data-mouse='{"op":"click","button":"LEFT"}'>左键</button><button data-mouse='{"op":"move","x":20,"y":0}'>→</button></div><div class="row" style="justify-content:center;margin:10px 0"><button data-mouse='{"op":"move","x":0,"y":20}'>↓</button><button data-mouse='{"op":"click","button":"RIGHT"}'>右键</button></div><div class="row" style="justify-content:center"><button data-mouse='{"op":"scroll","amount":-3}'>向上滚动</button><button data-mouse='{"op":"scroll","amount":3}'>向下滚动</button></div></section>
<section class="card"><h2>Macro 编辑器</h2><input id="macroId" type="hidden"><label>名称</label><input id="macroName" maxlength="48" placeholder="例如：插入签名"><label>动作（JSON 数组）</label><textarea id="actions">[
  {"type":"text","value":"Hello from AtomDeck-S3"},
  {"type":"key","value":"ENTER"}
]</textarea><div class="hint">允许 text、key、chord、delay 与受限鼠标动作；不支持脚本或系统命令。</div><div class="row" style="margin-top:12px"><button id="saveBtn">保存 Macro</button><button id="cancelBtn" class="secondary" type="button">清空</button></div></section>
<section class="card wide"><div class="row" style="justify-content:space-between"><h2>已保存的 Macro</h2><button id="refreshBtn" class="secondary">刷新</button></div><div id="macros"><span class="hint">正在加载…</span></div></section></div></div><div id="toast"></div>
<script>
const $=s=>document.querySelector(s);let state={},macros=[];function toast(m,bad=false){const t=$('#toast');t.textContent=m;t.className=bad?'error':'ok';t.style.display='block';setTimeout(()=>t.style.display='none',3500)}async function api(path,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};const r=await fetch(path,opt);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function status(){state=await api('/api/v1/status');$('#device').textContent=`${state.hostname} · ${state.wifi.ip} · ${state.wifi.mode}`;const a=$('#armed');a.textContent=state.armed?`已授权 · ${state.armed_seconds} 秒`:'未授权 · 请按设备按钮';a.classList.toggle('on',state.armed);$('#setup').hidden=!state.setup_mode;$('#main').hidden=state.setup_mode;document.querySelectorAll('#main button:not(#refreshBtn):not(#cancelBtn)').forEach(b=>b.disabled=!state.armed)}
function render(){const host=$('#macros');host.innerHTML='';if(!macros.length){host.innerHTML='<span class="hint">尚未保存 Macro。</span>';return}for(const m of macros){const el=document.createElement('div');el.className='macro';el.innerHTML=`<div><div class="name"></div><div class="meta"></div></div><div class="row"><button class="run">运行</button><button class="edit secondary">编辑</button><button class="del danger">删除</button></div>`;el.querySelector('.name').textContent=m.name;el.querySelector('.meta').textContent=`${m.actions.length} 个动作 · ${m.id.slice(0,8)}`;el.querySelector('.run').disabled=!state.armed;el.querySelector('.edit').disabled=!state.armed;el.querySelector('.del').disabled=!state.armed;el.querySelector('.run').onclick=async()=>{try{await api(`/api/v1/macros/${m.id}/run`,{method:'POST'});toast('Macro 执行完成')}catch(e){toast(e.message,true)}};el.querySelector('.edit').onclick=()=>{$('#macroId').value=m.id;$('#macroName').value=m.name;$('#actions').value=JSON.stringify(m.actions,null,2);scrollTo({top:0,behavior:'smooth'})};el.querySelector('.del').onclick=async()=>{if(!confirm(`确定删除“${m.name}”？`))return;try{await api(`/api/v1/macros/${m.id}`,{method:'DELETE'});toast('Macro 已删除');await loadMacros()}catch(e){toast(e.message,true)}};host.append(el)}}
async function loadMacros(){macros=await api('/api/v1/macros');render()}function clearEditor(){$('#macroId').value='';$('#macroName').value='';$('#actions').value='[\n  {"type":"text","value":""}\n]'}
$('#saveBtn').onclick=async()=>{try{const payload={name:$('#macroName').value,actions:JSON.parse($('#actions').value)};const id=$('#macroId').value;await api(id?`/api/v1/macros/${id}`:'/api/v1/macros',{method:id?'PUT':'POST',body:JSON.stringify(payload)});toast(id?'Macro 已更新':'Macro 已创建');clearEditor();await loadMacros()}catch(e){toast(e.message,true)}};$('#cancelBtn').onclick=clearEditor;$('#refreshBtn').onclick=async()=>{try{await Promise.all([status(),loadMacros()])}catch(e){toast(e.message,true)}};$('#typeBtn').onclick=async()=>{try{await api('/api/v1/type',{method:'POST',body:JSON.stringify({text:$('#directText').value})});toast('文本已输入')}catch(e){toast(e.message,true)}};
$('#wifiForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/v1/wifi',{method:'POST',body:JSON.stringify({ssid:$('#ssid').value,password:$('#password').value})});$('#password').value='';toast('已保存，设备正在重启…')}catch(err){$('#password').value='';toast(err.message,true)}};
document.querySelectorAll('[data-mouse]').forEach(b=>b.onclick=async()=>{try{await api('/api/v1/mouse',{method:'POST',body:b.dataset.mouse});toast('鼠标命令已发送')}catch(e){toast(e.message,true)}});
(async()=>{try{await status();if(!state.setup_mode)await loadMacros();setInterval(async()=>{try{await status();if(!state.setup_mode)render()}catch{}},1000)}catch(e){toast(e.message,true)}})();
</script></body></html>
)ATOMDECKHTML";
